### ISSUE TITLE
엔티티 삭제하는 함수를 만들어주세요.

### ISSUE THREAD

**Issue by droplet92** [CartoonIsArt/CIAPI#54]
특히 유저 삭제 부분의 코드가 너무 깁니다.

**Comment by droplet92** [comment]
해당 엔티티를 비활성화한다는 뜻이 정확히 이해가지 않습니다.
유저와 다른 엔티티 사이의 관계를 해제한다는 뜻으로 받아들이면 될까요?

그렇게 하면 기존 작성글/댓글의 유저에는 null이 들어갑니다. 예를 들면
`document.author = null` 과 같이 직접 null을 대입하는 방법이나

```
await conn.
createQueryBuilder()
.relation(Comments, "author")
.of(comment)
.set(null)
```
위 코드처럼 relation을 이용하여 해제하면 될 것 같습니다.

다른 방법이라면 알려주세요.

**Comment by kswgit** [comment]
"탈퇴한 회원" 가상 계정을 만들어서 삭제요청시 해당 회원으로 릴레이션을 맺게 하면 어떨까요

**Comment by droplet92** [comment]
가상 계정을 만들고 아래와 같은 방식으로 하면 될 것 같습니다.
코드 및 스펙문서 수정 후 머지하겠습니다.

1. 스펙 문서에 '탈퇴한 회원' 표기
2. DB에 해당 데이터 추가
3. DELETE 요청 시, 탈퇴한 회원으로 릴레이션 변경
4. git에 DB폴더 업로드 (.gitignore에서 잠시 DB 삭제)

**Comment by droplet92** [comment]
탈퇴한 회원은 함수로 추가하면 될까요 아니면 DB에 바로 추가해도 될까요?

**Comment by droplet92** [comment]
DB 0번 유저를 디폴트 유저 (탈퇴 유저)로 설정하고 릴레이션을 이족으로 연결하는 식으로 구현했습니다.
해결되었다고 생각하므로 이슈 닫습니다. 문제가 있다면 재오픈해주세요.
