### ISSUE TITLE
로그인시 Session테이블에 쿠키가 매번 저장됨

### ISSUE THREAD

**Issue by sGOM** [CartoonIsArt/CIAPI#88]
로그인시 같은 UserId임에도 불구하고 새로운 Cookie들이 쌓임

같은 UserId라면 기존의 Cookie를 업데이트하는 방향으로 고치면 좋을듯

**Comment by droplet92** [comment]
#132 에서 로그아웃 기능 구현.
로그인할 때마다 authenticationToken을 쌓고, 로그아웃하면 DB에서 삭제.
